services:
  optimeal-app:
    container_name: optimeal-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@optimeal-db:5432/optimeal?schema=public
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      optimeal-db:
        condition: service_healthy
    command: sh -c "echo 'Waiting for database to be ready...' && sleep 5 && echo 'Generating Prisma client...' && npx prisma generate && echo 'Pushing database schema...' && npx prisma db push && echo 'Starting application...' && npm run dev"
    volumes:
      # Mount source code for development (hot reloading)
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - optimeal-network

  optimeal-db:
    container_name: optimeal-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=optimeal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - optimeal-network


  # Optional: Prisma Studio for database management
  studio:
    container_name: optimeal-studio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:password@optimeal-db:5432/optimeal?schema=public
    depends_on:
      - optimeal-db
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    profiles:
      - tools
    networks:
      - optimeal-network

volumes:
  postgres_data:

networks:
  optimeal-network:
    driver: bridge
